### ISSUE TITLE
请问为什么我的actions没有任何反应？

### ISSUE THREAD

**Issue by Forgo7ten** [qianx443/dkd#3]
![image](https://user-images.githubusercontent.com/57509907/107049608-46fc5800-6805-11eb-9981-e33e1aa1ed8a.png)

**Comment by Forgo7ten** [comment]
添加Secrets的时候。假如我想输入dkdurl，是输入 'http://dkd-api.dysdk.com/user/index' 还是输入 http://dkd-api.dysdk.com/user/index 呢？有没有引号呀？

**Comment by qianx443** [comment]
1、不需要输入 引号
2、请确认enable workflow, 修改下readme.md并提交commit change

**Comment by Forgo7ten** [comment]
> 1、不需要输入 引号
> 2、请确认enable workflow, 修改下readme.md并提交commit change

感谢，已成功。但是Server酱推送功能好像没有作用。我使用的是微信端server酱，查看运行结果时候也没有提示代码中所含有的“server酱:发送失败”或者成功
